// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: control_center.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_CREATE         Status = 1
	Status_UPDATE         Status = 2
	Status_DELETE         Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "CREATE",
		2: "UPDATE",
		3: "DELETE",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"CREATE":         1,
		"UPDATE":         2,
		"DELETE":         3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_control_center_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_control_center_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_control_center_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_TYPE_UNKNOWN Type = 0
	Type_SERVERPOOL   Type = 1
	Type_SERVER       Type = 2
	Type_CONFIG       Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "SERVERPOOL",
		2: "SERVER",
		3: "CONFIG",
	}
	Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"SERVERPOOL":   1,
		"SERVER":       2,
		"CONFIG":       3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_control_center_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_control_center_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_control_center_proto_rawDescGZIP(), []int{1}
}

type RessourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RessourceRequest) Reset() {
	*x = RessourceRequest{}
	mi := &file_control_center_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RessourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RessourceRequest) ProtoMessage() {}

func (x *RessourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_center_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RessourceRequest.ProtoReflect.Descriptor instead.
func (*RessourceRequest) Descriptor() ([]byte, []int) {
	return file_control_center_proto_rawDescGZIP(), []int{0}
}

func (x *RessourceRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *RessourceRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type RessourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RessourceResponse) Reset() {
	*x = RessourceResponse{}
	mi := &file_control_center_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RessourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RessourceResponse) ProtoMessage() {}

func (x *RessourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_center_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RessourceResponse.ProtoReflect.Descriptor instead.
func (*RessourceResponse) Descriptor() ([]byte, []int) {
	return file_control_center_proto_rawDescGZIP(), []int{1}
}

func (x *RessourceResponse) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *RessourceResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamRessourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=controlcenter.Status" json:"status,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRessourceResponse) Reset() {
	*x = StreamRessourceResponse{}
	mi := &file_control_center_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRessourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRessourceResponse) ProtoMessage() {}

func (x *StreamRessourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_center_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRessourceResponse.ProtoReflect.Descriptor instead.
func (*StreamRessourceResponse) Descriptor() ([]byte, []int) {
	return file_control_center_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRessourceResponse) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *StreamRessourceResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *StreamRessourceResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_control_center_proto protoreflect.FileDescriptor

const file_control_center_proto_rawDesc = "" +
	"\n" +
	"\x14control_center.proto\x12\rcontrolcenter\"\xa2\x01\n" +
	"\x10RessourceRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12=\n" +
	"\x04data\x18\x02 \x03(\v2).controlcenter.RessourceRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x11RessourceResponse\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12>\n" +
	"\x04data\x18\x02 \x03(\v2*.controlcenter.RessourceResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x01\n" +
	"\x17StreamRessourceResponse\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.controlcenter.StatusR\x06status\x12D\n" +
	"\x04data\x18\x03 \x03(\v20.controlcenter.StreamRessourceResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*@\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03*@\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"SERVERPOOL\x10\x01\x12\n" +
	"\n" +
	"\x06SERVER\x10\x02\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x032\x9e\x02\n" +
	"\rControlCenter\x12R\n" +
	"\rGetRessources\x12\x1f.controlcenter.RessourceRequest\x1a .controlcenter.RessourceResponse\x12Z\n" +
	"\x13GetStreamRessources\x12\x1f.controlcenter.RessourceRequest\x1a .controlcenter.RessourceResponse0\x01\x12]\n" +
	"\x10GetStreamUpdates\x12\x1f.controlcenter.RessourceRequest\x1a&.controlcenter.StreamRessourceResponse0\x01B\x17Z\x15project/backend/pb;pbb\x06proto3"

var (
	file_control_center_proto_rawDescOnce sync.Once
	file_control_center_proto_rawDescData []byte
)

func file_control_center_proto_rawDescGZIP() []byte {
	file_control_center_proto_rawDescOnce.Do(func() {
		file_control_center_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_center_proto_rawDesc), len(file_control_center_proto_rawDesc)))
	})
	return file_control_center_proto_rawDescData
}

var file_control_center_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_control_center_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_control_center_proto_goTypes = []any{
	(Status)(0),                     // 0: controlcenter.Status
	(Type)(0),                       // 1: controlcenter.Type
	(*RessourceRequest)(nil),        // 2: controlcenter.RessourceRequest
	(*RessourceResponse)(nil),       // 3: controlcenter.RessourceResponse
	(*StreamRessourceResponse)(nil), // 4: controlcenter.StreamRessourceResponse
	nil,                             // 5: controlcenter.RessourceRequest.DataEntry
	nil,                             // 6: controlcenter.RessourceResponse.DataEntry
	nil,                             // 7: controlcenter.StreamRessourceResponse.DataEntry
}
var file_control_center_proto_depIdxs = []int32{
	5, // 0: controlcenter.RessourceRequest.data:type_name -> controlcenter.RessourceRequest.DataEntry
	6, // 1: controlcenter.RessourceResponse.data:type_name -> controlcenter.RessourceResponse.DataEntry
	0, // 2: controlcenter.StreamRessourceResponse.status:type_name -> controlcenter.Status
	7, // 3: controlcenter.StreamRessourceResponse.data:type_name -> controlcenter.StreamRessourceResponse.DataEntry
	2, // 4: controlcenter.ControlCenter.GetRessources:input_type -> controlcenter.RessourceRequest
	2, // 5: controlcenter.ControlCenter.GetStreamRessources:input_type -> controlcenter.RessourceRequest
	2, // 6: controlcenter.ControlCenter.GetStreamUpdates:input_type -> controlcenter.RessourceRequest
	3, // 7: controlcenter.ControlCenter.GetRessources:output_type -> controlcenter.RessourceResponse
	3, // 8: controlcenter.ControlCenter.GetStreamRessources:output_type -> controlcenter.RessourceResponse
	4, // 9: controlcenter.ControlCenter.GetStreamUpdates:output_type -> controlcenter.StreamRessourceResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_control_center_proto_init() }
func file_control_center_proto_init() {
	if File_control_center_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_center_proto_rawDesc), len(file_control_center_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_center_proto_goTypes,
		DependencyIndexes: file_control_center_proto_depIdxs,
		EnumInfos:         file_control_center_proto_enumTypes,
		MessageInfos:      file_control_center_proto_msgTypes,
	}.Build()
	File_control_center_proto = out.File
	file_control_center_proto_goTypes = nil
	file_control_center_proto_depIdxs = nil
}
