# A table

[server]

Name = "test"
MinServer = 3
MaxServer = 10
ImageRef = "72d05dc3-73ec-405b-b870-48f70782526f"
FlavorRef = "a69d1ae1-74cf-4750-8f8c-a621a39f8e24"
UUID = "94e241e7-77d3-46e2-b6b7-f87d97d0a28e"
Subnet = "fda5f48f-a66e-43a5-8c39-24c598159fe9"
SecurityGroups = ["default"]
Keyname = "william"

[metadata]

serverpool-id = "PoolVms"
minVM = "2"
maxVM = "9"
userID = "admin"
pool-id = "PoolVMs"


[volume]

Size = 1
Description = "test"
Name = "test"
Volumetype = "__DEFAULT__"

[network]

NetworkID = "39aa90ca-163b-4630-9671-9439fefe516f"