// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: poolmanager.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoolManager_SendRessources_FullMethodName          = "/poolmanager.PoolManager/SendRessources"
	PoolManager_GetStreamRessources_FullMethodName     = "/poolmanager.PoolManager/GetStreamRessources"
	PoolManager_GetStreamRessourcesUser_FullMethodName = "/poolmanager.PoolManager/GetStreamRessourcesUser"
	PoolManager_GetAllImages_FullMethodName            = "/poolmanager.PoolManager/GetAllImages"
	PoolManager_GetAllFlavors_FullMethodName           = "/poolmanager.PoolManager/GetAllFlavors"
	PoolManager_GetAllNetworks_FullMethodName          = "/poolmanager.PoolManager/GetAllNetworks"
)

// PoolManagerClient is the client API for PoolManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoolManagerClient interface {
	SendRessources(ctx context.Context, in *RessourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetStreamRessources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamRessourceResponse], error)
	GetStreamRessourcesUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamRessourceResponse], error)
	GetAllImages(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error)
	GetAllFlavors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flavor], error)
	GetAllNetworks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Network], error)
}

type poolManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolManagerClient(cc grpc.ClientConnInterface) PoolManagerClient {
	return &poolManagerClient{cc}
}

func (c *poolManagerClient) SendRessources(ctx context.Context, in *RessourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PoolManager_SendRessources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolManagerClient) GetStreamRessources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamRessourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolManager_ServiceDesc.Streams[0], PoolManager_GetStreamRessources_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, StreamRessourceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetStreamRessourcesClient = grpc.ServerStreamingClient[StreamRessourceResponse]

func (c *poolManagerClient) GetStreamRessourcesUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamRessourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolManager_ServiceDesc.Streams[1], PoolManager_GetStreamRessourcesUser_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserRequest, StreamRessourceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetStreamRessourcesUserClient = grpc.ServerStreamingClient[StreamRessourceResponse]

func (c *poolManagerClient) GetAllImages(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolManager_ServiceDesc.Streams[2], PoolManager_GetAllImages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Image]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetAllImagesClient = grpc.ServerStreamingClient[Image]

func (c *poolManagerClient) GetAllFlavors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flavor], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolManager_ServiceDesc.Streams[3], PoolManager_GetAllFlavors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Flavor]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetAllFlavorsClient = grpc.ServerStreamingClient[Flavor]

func (c *poolManagerClient) GetAllNetworks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Network], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolManager_ServiceDesc.Streams[4], PoolManager_GetAllNetworks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Network]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetAllNetworksClient = grpc.ServerStreamingClient[Network]

// PoolManagerServer is the server API for PoolManager service.
// All implementations must embed UnimplementedPoolManagerServer
// for forward compatibility.
type PoolManagerServer interface {
	SendRessources(context.Context, *RessourceRequest) (*emptypb.Empty, error)
	GetStreamRessources(*emptypb.Empty, grpc.ServerStreamingServer[StreamRessourceResponse]) error
	GetStreamRessourcesUser(*UserRequest, grpc.ServerStreamingServer[StreamRessourceResponse]) error
	GetAllImages(*emptypb.Empty, grpc.ServerStreamingServer[Image]) error
	GetAllFlavors(*emptypb.Empty, grpc.ServerStreamingServer[Flavor]) error
	GetAllNetworks(*emptypb.Empty, grpc.ServerStreamingServer[Network]) error
	mustEmbedUnimplementedPoolManagerServer()
}

// UnimplementedPoolManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolManagerServer struct{}

func (UnimplementedPoolManagerServer) SendRessources(context.Context, *RessourceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRessources not implemented")
}
func (UnimplementedPoolManagerServer) GetStreamRessources(*emptypb.Empty, grpc.ServerStreamingServer[StreamRessourceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetStreamRessources not implemented")
}
func (UnimplementedPoolManagerServer) GetStreamRessourcesUser(*UserRequest, grpc.ServerStreamingServer[StreamRessourceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetStreamRessourcesUser not implemented")
}
func (UnimplementedPoolManagerServer) GetAllImages(*emptypb.Empty, grpc.ServerStreamingServer[Image]) error {
	return status.Errorf(codes.Unimplemented, "method GetAllImages not implemented")
}
func (UnimplementedPoolManagerServer) GetAllFlavors(*emptypb.Empty, grpc.ServerStreamingServer[Flavor]) error {
	return status.Errorf(codes.Unimplemented, "method GetAllFlavors not implemented")
}
func (UnimplementedPoolManagerServer) GetAllNetworks(*emptypb.Empty, grpc.ServerStreamingServer[Network]) error {
	return status.Errorf(codes.Unimplemented, "method GetAllNetworks not implemented")
}
func (UnimplementedPoolManagerServer) mustEmbedUnimplementedPoolManagerServer() {}
func (UnimplementedPoolManagerServer) testEmbeddedByValue()                     {}

// UnsafePoolManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolManagerServer will
// result in compilation errors.
type UnsafePoolManagerServer interface {
	mustEmbedUnimplementedPoolManagerServer()
}

func RegisterPoolManagerServer(s grpc.ServiceRegistrar, srv PoolManagerServer) {
	// If the following call pancis, it indicates UnimplementedPoolManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolManager_ServiceDesc, srv)
}

func _PoolManager_SendRessources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RessourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolManagerServer).SendRessources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolManager_SendRessources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolManagerServer).SendRessources(ctx, req.(*RessourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolManager_GetStreamRessources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PoolManagerServer).GetStreamRessources(m, &grpc.GenericServerStream[emptypb.Empty, StreamRessourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetStreamRessourcesServer = grpc.ServerStreamingServer[StreamRessourceResponse]

func _PoolManager_GetStreamRessourcesUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PoolManagerServer).GetStreamRessourcesUser(m, &grpc.GenericServerStream[UserRequest, StreamRessourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetStreamRessourcesUserServer = grpc.ServerStreamingServer[StreamRessourceResponse]

func _PoolManager_GetAllImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PoolManagerServer).GetAllImages(m, &grpc.GenericServerStream[emptypb.Empty, Image]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetAllImagesServer = grpc.ServerStreamingServer[Image]

func _PoolManager_GetAllFlavors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PoolManagerServer).GetAllFlavors(m, &grpc.GenericServerStream[emptypb.Empty, Flavor]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetAllFlavorsServer = grpc.ServerStreamingServer[Flavor]

func _PoolManager_GetAllNetworks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PoolManagerServer).GetAllNetworks(m, &grpc.GenericServerStream[emptypb.Empty, Network]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolManager_GetAllNetworksServer = grpc.ServerStreamingServer[Network]

// PoolManager_ServiceDesc is the grpc.ServiceDesc for PoolManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poolmanager.PoolManager",
	HandlerType: (*PoolManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRessources",
			Handler:    _PoolManager_SendRessources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStreamRessources",
			Handler:       _PoolManager_GetStreamRessources_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStreamRessourcesUser",
			Handler:       _PoolManager_GetStreamRessourcesUser_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllImages",
			Handler:       _PoolManager_GetAllImages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllFlavors",
			Handler:       _PoolManager_GetAllFlavors_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllNetworks",
			Handler:       _PoolManager_GetAllNetworks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "poolmanager.proto",
}
