/**
 * @fileoverview gRPC-Web generated client stub for controlcenter
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.0
// source: control_center.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as control_center_pb from './control_center_pb'; // proto import: "control_center.proto"


export class ControlCenterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetRessources = new grpcWeb.MethodDescriptor(
    '/controlcenter.ControlCenter/GetRessources',
    grpcWeb.MethodType.UNARY,
    control_center_pb.RessourceRequest,
    control_center_pb.RessourceResponse,
    (request: control_center_pb.RessourceRequest) => {
      return request.serializeBinary();
    },
    control_center_pb.RessourceResponse.deserializeBinary
  );

  getRessources(
    request: control_center_pb.RessourceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<control_center_pb.RessourceResponse>;

  getRessources(
    request: control_center_pb.RessourceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: control_center_pb.RessourceResponse) => void): grpcWeb.ClientReadableStream<control_center_pb.RessourceResponse>;

  getRessources(
    request: control_center_pb.RessourceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: control_center_pb.RessourceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/controlcenter.ControlCenter/GetRessources',
        request,
        metadata || {},
        this.methodDescriptorGetRessources,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/controlcenter.ControlCenter/GetRessources',
    request,
    metadata || {},
    this.methodDescriptorGetRessources);
  }

  methodDescriptorGetStreamRessources = new grpcWeb.MethodDescriptor(
    '/controlcenter.ControlCenter/GetStreamRessources',
    grpcWeb.MethodType.SERVER_STREAMING,
    control_center_pb.RessourceRequest,
    control_center_pb.RessourceResponse,
    (request: control_center_pb.RessourceRequest) => {
      return request.serializeBinary();
    },
    control_center_pb.RessourceResponse.deserializeBinary
  );

  getStreamRessources(
    request: control_center_pb.RessourceRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<control_center_pb.RessourceResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/controlcenter.ControlCenter/GetStreamRessources',
      request,
      metadata || {},
      this.methodDescriptorGetStreamRessources);
  }

  methodDescriptorGetStreamUpdates = new grpcWeb.MethodDescriptor(
    '/controlcenter.ControlCenter/GetStreamUpdates',
    grpcWeb.MethodType.SERVER_STREAMING,
    control_center_pb.RessourceRequest,
    control_center_pb.StreamRessourceResponse,
    (request: control_center_pb.RessourceRequest) => {
      return request.serializeBinary();
    },
    control_center_pb.StreamRessourceResponse.deserializeBinary
  );

  getStreamUpdates(
    request: control_center_pb.RessourceRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<control_center_pb.StreamRessourceResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/controlcenter.ControlCenter/GetStreamUpdates',
      request,
      metadata || {},
      this.methodDescriptorGetStreamUpdates);
  }

}

