/**
 * @fileoverview gRPC-Web generated client stub for frontcontrol
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.0
// source: frontcontrol.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as frontcontrol_pb from './frontcontrol_pb'; // proto import: "frontcontrol.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/frontcontrol.AuthService/CreateUser',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.CreateUserRequest,
    frontcontrol_pb.CreateUserResponse,
    (request: frontcontrol_pb.CreateUserRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.CreateUserResponse.deserializeBinary
  );

  createUser(
    request: frontcontrol_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.CreateUserResponse>;

  createUser(
    request: frontcontrol_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.CreateUserResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.CreateUserResponse>;

  createUser(
    request: frontcontrol_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.CreateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.AuthService/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.AuthService/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

  methodDescriptorAuthenticateUser = new grpcWeb.MethodDescriptor(
    '/frontcontrol.AuthService/AuthenticateUser',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.AuthenticateUserRequest,
    frontcontrol_pb.AuthenticateUserResponse,
    (request: frontcontrol_pb.AuthenticateUserRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.AuthenticateUserResponse.deserializeBinary
  );

  authenticateUser(
    request: frontcontrol_pb.AuthenticateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.AuthenticateUserResponse>;

  authenticateUser(
    request: frontcontrol_pb.AuthenticateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.AuthenticateUserResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.AuthenticateUserResponse>;

  authenticateUser(
    request: frontcontrol_pb.AuthenticateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.AuthenticateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.AuthService/AuthenticateUser',
        request,
        metadata || {},
        this.methodDescriptorAuthenticateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.AuthService/AuthenticateUser',
    request,
    metadata || {},
    this.methodDescriptorAuthenticateUser);
  }

}

export class GatherDataServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAllImages = new grpcWeb.MethodDescriptor(
    '/frontcontrol.GatherDataService/GetAllImages',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    frontcontrol_pb.Image,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.Image.deserializeBinary
  );

  getAllImages(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<frontcontrol_pb.Image> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/frontcontrol.GatherDataService/GetAllImages',
      request,
      metadata || {},
      this.methodDescriptorGetAllImages);
  }

  methodDescriptorGetAllFlavors = new grpcWeb.MethodDescriptor(
    '/frontcontrol.GatherDataService/GetAllFlavors',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    frontcontrol_pb.Flavor,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.Flavor.deserializeBinary
  );

  getAllFlavors(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<frontcontrol_pb.Flavor> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/frontcontrol.GatherDataService/GetAllFlavors',
      request,
      metadata || {},
      this.methodDescriptorGetAllFlavors);
  }

  methodDescriptorGetAllNetworks = new grpcWeb.MethodDescriptor(
    '/frontcontrol.GatherDataService/GetAllNetworks',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    frontcontrol_pb.Network,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.Network.deserializeBinary
  );

  getAllNetworks(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<frontcontrol_pb.Network> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/frontcontrol.GatherDataService/GetAllNetworks',
      request,
      metadata || {},
      this.methodDescriptorGetAllNetworks);
  }

  methodDescriptorGetAllServers = new grpcWeb.MethodDescriptor(
    '/frontcontrol.GatherDataService/GetAllServers',
    grpcWeb.MethodType.SERVER_STREAMING,
    frontcontrol_pb.UserRequest,
    frontcontrol_pb.Server,
    (request: frontcontrol_pb.UserRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.Server.deserializeBinary
  );

  getAllServers(
    request: frontcontrol_pb.UserRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<frontcontrol_pb.Server> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/frontcontrol.GatherDataService/GetAllServers',
      request,
      metadata || {},
      this.methodDescriptorGetAllServers);
  }

  methodDescriptorGetAllServerPools = new grpcWeb.MethodDescriptor(
    '/frontcontrol.GatherDataService/GetAllServerPools',
    grpcWeb.MethodType.SERVER_STREAMING,
    frontcontrol_pb.UserRequest,
    frontcontrol_pb.ServerPool,
    (request: frontcontrol_pb.UserRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.ServerPool.deserializeBinary
  );

  getAllServerPools(
    request: frontcontrol_pb.UserRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<frontcontrol_pb.ServerPool> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/frontcontrol.GatherDataService/GetAllServerPools',
      request,
      metadata || {},
      this.methodDescriptorGetAllServerPools);
  }

}

export class ConfigServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateConfig = new grpcWeb.MethodDescriptor(
    '/frontcontrol.ConfigService/CreateConfig',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.CreateConfigRequest,
    frontcontrol_pb.CreateConfigResponse,
    (request: frontcontrol_pb.CreateConfigRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.CreateConfigResponse.deserializeBinary
  );

  createConfig(
    request: frontcontrol_pb.CreateConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.CreateConfigResponse>;

  createConfig(
    request: frontcontrol_pb.CreateConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.CreateConfigResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.CreateConfigResponse>;

  createConfig(
    request: frontcontrol_pb.CreateConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.CreateConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.ConfigService/CreateConfig',
        request,
        metadata || {},
        this.methodDescriptorCreateConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.ConfigService/CreateConfig',
    request,
    metadata || {},
    this.methodDescriptorCreateConfig);
  }

  methodDescriptorUpdateConfig = new grpcWeb.MethodDescriptor(
    '/frontcontrol.ConfigService/UpdateConfig',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.UpdateConfigRequest,
    frontcontrol_pb.UpdateConfigResponse,
    (request: frontcontrol_pb.UpdateConfigRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.UpdateConfigResponse.deserializeBinary
  );

  updateConfig(
    request: frontcontrol_pb.UpdateConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.UpdateConfigResponse>;

  updateConfig(
    request: frontcontrol_pb.UpdateConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.UpdateConfigResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.UpdateConfigResponse>;

  updateConfig(
    request: frontcontrol_pb.UpdateConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.UpdateConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.ConfigService/UpdateConfig',
        request,
        metadata || {},
        this.methodDescriptorUpdateConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.ConfigService/UpdateConfig',
    request,
    metadata || {},
    this.methodDescriptorUpdateConfig);
  }

  methodDescriptorDeleteConfig = new grpcWeb.MethodDescriptor(
    '/frontcontrol.ConfigService/DeleteConfig',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.DeleteConfigRequest,
    frontcontrol_pb.DeleteConfigResponse,
    (request: frontcontrol_pb.DeleteConfigRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.DeleteConfigResponse.deserializeBinary
  );

  deleteConfig(
    request: frontcontrol_pb.DeleteConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.DeleteConfigResponse>;

  deleteConfig(
    request: frontcontrol_pb.DeleteConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.DeleteConfigResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.DeleteConfigResponse>;

  deleteConfig(
    request: frontcontrol_pb.DeleteConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.DeleteConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.ConfigService/DeleteConfig',
        request,
        metadata || {},
        this.methodDescriptorDeleteConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.ConfigService/DeleteConfig',
    request,
    metadata || {},
    this.methodDescriptorDeleteConfig);
  }

  methodDescriptorGetConfig = new grpcWeb.MethodDescriptor(
    '/frontcontrol.ConfigService/GetConfig',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.GetConfigRequest,
    frontcontrol_pb.GetConfigResponse,
    (request: frontcontrol_pb.GetConfigRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.GetConfigResponse.deserializeBinary
  );

  getConfig(
    request: frontcontrol_pb.GetConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.GetConfigResponse>;

  getConfig(
    request: frontcontrol_pb.GetConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.GetConfigResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.GetConfigResponse>;

  getConfig(
    request: frontcontrol_pb.GetConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.GetConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.ConfigService/GetConfig',
        request,
        metadata || {},
        this.methodDescriptorGetConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.ConfigService/GetConfig',
    request,
    metadata || {},
    this.methodDescriptorGetConfig);
  }

  methodDescriptorGetAllConfigs = new grpcWeb.MethodDescriptor(
    '/frontcontrol.ConfigService/GetAllConfigs',
    grpcWeb.MethodType.SERVER_STREAMING,
    frontcontrol_pb.GetConfigRequest,
    frontcontrol_pb.GetConfigResponse,
    (request: frontcontrol_pb.GetConfigRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.GetConfigResponse.deserializeBinary
  );

  getAllConfigs(
    request: frontcontrol_pb.GetConfigRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<frontcontrol_pb.GetConfigResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/frontcontrol.ConfigService/GetAllConfigs',
      request,
      metadata || {},
      this.methodDescriptorGetAllConfigs);
  }

}

export class PoolServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreatePool = new grpcWeb.MethodDescriptor(
    '/frontcontrol.PoolService/CreatePool',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.CreatePoolRequest,
    frontcontrol_pb.CreatePoolResponse,
    (request: frontcontrol_pb.CreatePoolRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.CreatePoolResponse.deserializeBinary
  );

  createPool(
    request: frontcontrol_pb.CreatePoolRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.CreatePoolResponse>;

  createPool(
    request: frontcontrol_pb.CreatePoolRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.CreatePoolResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.CreatePoolResponse>;

  createPool(
    request: frontcontrol_pb.CreatePoolRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.CreatePoolResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.PoolService/CreatePool',
        request,
        metadata || {},
        this.methodDescriptorCreatePool,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.PoolService/CreatePool',
    request,
    metadata || {},
    this.methodDescriptorCreatePool);
  }

  methodDescriptorGetPool = new grpcWeb.MethodDescriptor(
    '/frontcontrol.PoolService/GetPool',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.GetPoolRequest,
    frontcontrol_pb.GetPoolResponse,
    (request: frontcontrol_pb.GetPoolRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.GetPoolResponse.deserializeBinary
  );

  getPool(
    request: frontcontrol_pb.GetPoolRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.GetPoolResponse>;

  getPool(
    request: frontcontrol_pb.GetPoolRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.GetPoolResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.GetPoolResponse>;

  getPool(
    request: frontcontrol_pb.GetPoolRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.GetPoolResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.PoolService/GetPool',
        request,
        metadata || {},
        this.methodDescriptorGetPool,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.PoolService/GetPool',
    request,
    metadata || {},
    this.methodDescriptorGetPool);
  }

  methodDescriptorGetAllPools = new grpcWeb.MethodDescriptor(
    '/frontcontrol.PoolService/GetAllPools',
    grpcWeb.MethodType.SERVER_STREAMING,
    frontcontrol_pb.GetPoolRequest,
    frontcontrol_pb.GetPoolResponse,
    (request: frontcontrol_pb.GetPoolRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.GetPoolResponse.deserializeBinary
  );

  getAllPools(
    request: frontcontrol_pb.GetPoolRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<frontcontrol_pb.GetPoolResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/frontcontrol.PoolService/GetAllPools',
      request,
      metadata || {},
      this.methodDescriptorGetAllPools);
  }

  methodDescriptorDeletePool = new grpcWeb.MethodDescriptor(
    '/frontcontrol.PoolService/DeletePool',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.DeletePoolRequest,
    frontcontrol_pb.DeletePoolResponse,
    (request: frontcontrol_pb.DeletePoolRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.DeletePoolResponse.deserializeBinary
  );

  deletePool(
    request: frontcontrol_pb.DeletePoolRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.DeletePoolResponse>;

  deletePool(
    request: frontcontrol_pb.DeletePoolRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.DeletePoolResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.DeletePoolResponse>;

  deletePool(
    request: frontcontrol_pb.DeletePoolRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.DeletePoolResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.PoolService/DeletePool',
        request,
        metadata || {},
        this.methodDescriptorDeletePool,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.PoolService/DeletePool',
    request,
    metadata || {},
    this.methodDescriptorDeletePool);
  }

  methodDescriptorRebuildServer = new grpcWeb.MethodDescriptor(
    '/frontcontrol.PoolService/RebuildServer',
    grpcWeb.MethodType.UNARY,
    frontcontrol_pb.RebuildServerRequest,
    frontcontrol_pb.RebuildServerResponse,
    (request: frontcontrol_pb.RebuildServerRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.RebuildServerResponse.deserializeBinary
  );

  rebuildServer(
    request: frontcontrol_pb.RebuildServerRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontcontrol_pb.RebuildServerResponse>;

  rebuildServer(
    request: frontcontrol_pb.RebuildServerRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.RebuildServerResponse) => void): grpcWeb.ClientReadableStream<frontcontrol_pb.RebuildServerResponse>;

  rebuildServer(
    request: frontcontrol_pb.RebuildServerRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontcontrol_pb.RebuildServerResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/frontcontrol.PoolService/RebuildServer',
        request,
        metadata || {},
        this.methodDescriptorRebuildServer,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/frontcontrol.PoolService/RebuildServer',
    request,
    metadata || {},
    this.methodDescriptorRebuildServer);
  }

}

export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUpdateDataUser = new grpcWeb.MethodDescriptor(
    '/frontcontrol.UserService/UpdateDataUser',
    grpcWeb.MethodType.SERVER_STREAMING,
    frontcontrol_pb.UpdateDataUserRequest,
    frontcontrol_pb.UpdateDataUserResponse,
    (request: frontcontrol_pb.UpdateDataUserRequest) => {
      return request.serializeBinary();
    },
    frontcontrol_pb.UpdateDataUserResponse.deserializeBinary
  );

  updateDataUser(
    request: frontcontrol_pb.UpdateDataUserRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<frontcontrol_pb.UpdateDataUserResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/frontcontrol.UserService/UpdateDataUser',
      request,
      metadata || {},
      this.methodDescriptorUpdateDataUser);
  }

}

