// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: control_center.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlCenter_GetRessources_FullMethodName       = "/controlcenter.ControlCenter/GetRessources"
	ControlCenter_GetStreamRessources_FullMethodName = "/controlcenter.ControlCenter/GetStreamRessources"
	ControlCenter_GetStreamUpdates_FullMethodName    = "/controlcenter.ControlCenter/GetStreamUpdates"
)

// ControlCenterClient is the client API for ControlCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlCenterClient interface {
	GetRessources(ctx context.Context, in *RessourceRequest, opts ...grpc.CallOption) (*RessourceResponse, error)
	GetStreamRessources(ctx context.Context, in *RessourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RessourceResponse], error)
	GetStreamUpdates(ctx context.Context, in *RessourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamRessourceResponse], error)
}

type controlCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewControlCenterClient(cc grpc.ClientConnInterface) ControlCenterClient {
	return &controlCenterClient{cc}
}

func (c *controlCenterClient) GetRessources(ctx context.Context, in *RessourceRequest, opts ...grpc.CallOption) (*RessourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RessourceResponse)
	err := c.cc.Invoke(ctx, ControlCenter_GetRessources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) GetStreamRessources(ctx context.Context, in *RessourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RessourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlCenter_ServiceDesc.Streams[0], ControlCenter_GetStreamRessources_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RessourceRequest, RessourceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlCenter_GetStreamRessourcesClient = grpc.ServerStreamingClient[RessourceResponse]

func (c *controlCenterClient) GetStreamUpdates(ctx context.Context, in *RessourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamRessourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlCenter_ServiceDesc.Streams[1], ControlCenter_GetStreamUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RessourceRequest, StreamRessourceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlCenter_GetStreamUpdatesClient = grpc.ServerStreamingClient[StreamRessourceResponse]

// ControlCenterServer is the server API for ControlCenter service.
// All implementations must embed UnimplementedControlCenterServer
// for forward compatibility.
type ControlCenterServer interface {
	GetRessources(context.Context, *RessourceRequest) (*RessourceResponse, error)
	GetStreamRessources(*RessourceRequest, grpc.ServerStreamingServer[RessourceResponse]) error
	GetStreamUpdates(*RessourceRequest, grpc.ServerStreamingServer[StreamRessourceResponse]) error
	mustEmbedUnimplementedControlCenterServer()
}

// UnimplementedControlCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlCenterServer struct{}

func (UnimplementedControlCenterServer) GetRessources(context.Context, *RessourceRequest) (*RessourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRessources not implemented")
}
func (UnimplementedControlCenterServer) GetStreamRessources(*RessourceRequest, grpc.ServerStreamingServer[RessourceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetStreamRessources not implemented")
}
func (UnimplementedControlCenterServer) GetStreamUpdates(*RessourceRequest, grpc.ServerStreamingServer[StreamRessourceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetStreamUpdates not implemented")
}
func (UnimplementedControlCenterServer) mustEmbedUnimplementedControlCenterServer() {}
func (UnimplementedControlCenterServer) testEmbeddedByValue()                       {}

// UnsafeControlCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlCenterServer will
// result in compilation errors.
type UnsafeControlCenterServer interface {
	mustEmbedUnimplementedControlCenterServer()
}

func RegisterControlCenterServer(s grpc.ServiceRegistrar, srv ControlCenterServer) {
	// If the following call pancis, it indicates UnimplementedControlCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlCenter_ServiceDesc, srv)
}

func _ControlCenter_GetRessources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RessourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).GetRessources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_GetRessources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).GetRessources(ctx, req.(*RessourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_GetStreamRessources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RessourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlCenterServer).GetStreamRessources(m, &grpc.GenericServerStream[RessourceRequest, RessourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlCenter_GetStreamRessourcesServer = grpc.ServerStreamingServer[RessourceResponse]

func _ControlCenter_GetStreamUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RessourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlCenterServer).GetStreamUpdates(m, &grpc.GenericServerStream[RessourceRequest, StreamRessourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlCenter_GetStreamUpdatesServer = grpc.ServerStreamingServer[StreamRessourceResponse]

// ControlCenter_ServiceDesc is the grpc.ServiceDesc for ControlCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlcenter.ControlCenter",
	HandlerType: (*ControlCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRessources",
			Handler:    _ControlCenter_GetRessources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStreamRessources",
			Handler:       _ControlCenter_GetStreamRessources_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStreamUpdates",
			Handler:       _ControlCenter_GetStreamUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control_center.proto",
}
