// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: frontcontrol.proto

package frontcontrolpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_CreateUser_FullMethodName       = "/frontcontrol.AuthService/CreateUser"
	AuthService_AuthenticateUser_FullMethodName = "/frontcontrol.AuthService/AuthenticateUser"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -------------------- Services --------------------
// AuthService manages user authentication and creation.
// Might change to use OIDC in the future.
type AuthServiceClient interface {
	// CreateUser creates a new user with the provided details.
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// AuthenticateUser verifies user credentials and returns an authentication token.
	AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateUserResponse)
	err := c.cc.Invoke(ctx, AuthService_AuthenticateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// -------------------- Services --------------------
// AuthService manages user authentication and creation.
// Might change to use OIDC in the future.
type AuthServiceServer interface {
	// CreateUser creates a new user with the provided details.
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// AuthenticateUser verifies user credentials and returns an authentication token.
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedAuthServiceServer) AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_AuthenticateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AuthenticateUser(ctx, req.(*AuthenticateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frontcontrol.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _AuthService_CreateUser_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _AuthService_AuthenticateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontcontrol.proto",
}

const (
	GatherDataService_GetAllImages_FullMethodName      = "/frontcontrol.GatherDataService/GetAllImages"
	GatherDataService_GetAllFlavors_FullMethodName     = "/frontcontrol.GatherDataService/GetAllFlavors"
	GatherDataService_GetAllNetworks_FullMethodName    = "/frontcontrol.GatherDataService/GetAllNetworks"
	GatherDataService_ExistServer_FullMethodName       = "/frontcontrol.GatherDataService/ExistServer"
	GatherDataService_ExistServerPools_FullMethodName  = "/frontcontrol.GatherDataService/ExistServerPools"
	GatherDataService_ExistConfigs_FullMethodName      = "/frontcontrol.GatherDataService/ExistConfigs"
	GatherDataService_GetAllServers_FullMethodName     = "/frontcontrol.GatherDataService/GetAllServers"
	GatherDataService_GetAllServerPools_FullMethodName = "/frontcontrol.GatherDataService/GetAllServerPools"
	GatherDataService_GetAllConfigs_FullMethodName     = "/frontcontrol.GatherDataService/GetAllConfigs"
)

// GatherDataServiceClient is the client API for GatherDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatherDataService retrieves various resources associated with a user
// and populates stores with datas (like images, flavors, networks).
type GatherDataServiceClient interface {
	// GetAllImages retrieves all images
	GetAllImages(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error)
	// GetAllFlavors retrieves all flavors
	GetAllFlavors(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flavor], error)
	// GetAllNetworks retrieves all networks
	GetAllNetworks(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Network], error)
	// ExistServer checks if a server exists for a user to open a stream
	ExistServer(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ExistData, error)
	// ExistServerPools checks if server pools exist for a user to open a stream
	ExistServerPools(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ExistData, error)
	// ExistConfigs checks if configs exist for a user to open a stream
	ExistConfigs(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ExistData, error)
	// GetAllServers retrieves all servers for a user
	GetAllServers(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Server], error)
	// GetAllServerPools retrieves all server pools for a user
	GetAllServerPools(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerPool], error)
	// GetAllConfigs retrieves all configs for a user
	GetAllConfigs(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Config], error)
}

type gatherDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatherDataServiceClient(cc grpc.ClientConnInterface) GatherDataServiceClient {
	return &gatherDataServiceClient{cc}
}

func (c *gatherDataServiceClient) GetAllImages(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatherDataService_ServiceDesc.Streams[0], GatherDataService_GetAllImages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserRequest, Image]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllImagesClient = grpc.ServerStreamingClient[Image]

func (c *gatherDataServiceClient) GetAllFlavors(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flavor], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatherDataService_ServiceDesc.Streams[1], GatherDataService_GetAllFlavors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserRequest, Flavor]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllFlavorsClient = grpc.ServerStreamingClient[Flavor]

func (c *gatherDataServiceClient) GetAllNetworks(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Network], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatherDataService_ServiceDesc.Streams[2], GatherDataService_GetAllNetworks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserRequest, Network]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllNetworksClient = grpc.ServerStreamingClient[Network]

func (c *gatherDataServiceClient) ExistServer(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ExistData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistData)
	err := c.cc.Invoke(ctx, GatherDataService_ExistServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatherDataServiceClient) ExistServerPools(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ExistData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistData)
	err := c.cc.Invoke(ctx, GatherDataService_ExistServerPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatherDataServiceClient) ExistConfigs(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ExistData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistData)
	err := c.cc.Invoke(ctx, GatherDataService_ExistConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatherDataServiceClient) GetAllServers(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Server], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatherDataService_ServiceDesc.Streams[3], GatherDataService_GetAllServers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserRequest, Server]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllServersClient = grpc.ServerStreamingClient[Server]

func (c *gatherDataServiceClient) GetAllServerPools(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerPool], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatherDataService_ServiceDesc.Streams[4], GatherDataService_GetAllServerPools_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserRequest, ServerPool]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllServerPoolsClient = grpc.ServerStreamingClient[ServerPool]

func (c *gatherDataServiceClient) GetAllConfigs(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Config], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatherDataService_ServiceDesc.Streams[5], GatherDataService_GetAllConfigs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserRequest, Config]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllConfigsClient = grpc.ServerStreamingClient[Config]

// GatherDataServiceServer is the server API for GatherDataService service.
// All implementations must embed UnimplementedGatherDataServiceServer
// for forward compatibility.
//
// GatherDataService retrieves various resources associated with a user
// and populates stores with datas (like images, flavors, networks).
type GatherDataServiceServer interface {
	// GetAllImages retrieves all images
	GetAllImages(*UserRequest, grpc.ServerStreamingServer[Image]) error
	// GetAllFlavors retrieves all flavors
	GetAllFlavors(*UserRequest, grpc.ServerStreamingServer[Flavor]) error
	// GetAllNetworks retrieves all networks
	GetAllNetworks(*UserRequest, grpc.ServerStreamingServer[Network]) error
	// ExistServer checks if a server exists for a user to open a stream
	ExistServer(context.Context, *UserRequest) (*ExistData, error)
	// ExistServerPools checks if server pools exist for a user to open a stream
	ExistServerPools(context.Context, *UserRequest) (*ExistData, error)
	// ExistConfigs checks if configs exist for a user to open a stream
	ExistConfigs(context.Context, *UserRequest) (*ExistData, error)
	// GetAllServers retrieves all servers for a user
	GetAllServers(*UserRequest, grpc.ServerStreamingServer[Server]) error
	// GetAllServerPools retrieves all server pools for a user
	GetAllServerPools(*UserRequest, grpc.ServerStreamingServer[ServerPool]) error
	// GetAllConfigs retrieves all configs for a user
	GetAllConfigs(*UserRequest, grpc.ServerStreamingServer[Config]) error
	mustEmbedUnimplementedGatherDataServiceServer()
}

// UnimplementedGatherDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatherDataServiceServer struct{}

func (UnimplementedGatherDataServiceServer) GetAllImages(*UserRequest, grpc.ServerStreamingServer[Image]) error {
	return status.Error(codes.Unimplemented, "method GetAllImages not implemented")
}
func (UnimplementedGatherDataServiceServer) GetAllFlavors(*UserRequest, grpc.ServerStreamingServer[Flavor]) error {
	return status.Error(codes.Unimplemented, "method GetAllFlavors not implemented")
}
func (UnimplementedGatherDataServiceServer) GetAllNetworks(*UserRequest, grpc.ServerStreamingServer[Network]) error {
	return status.Error(codes.Unimplemented, "method GetAllNetworks not implemented")
}
func (UnimplementedGatherDataServiceServer) ExistServer(context.Context, *UserRequest) (*ExistData, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistServer not implemented")
}
func (UnimplementedGatherDataServiceServer) ExistServerPools(context.Context, *UserRequest) (*ExistData, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistServerPools not implemented")
}
func (UnimplementedGatherDataServiceServer) ExistConfigs(context.Context, *UserRequest) (*ExistData, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistConfigs not implemented")
}
func (UnimplementedGatherDataServiceServer) GetAllServers(*UserRequest, grpc.ServerStreamingServer[Server]) error {
	return status.Error(codes.Unimplemented, "method GetAllServers not implemented")
}
func (UnimplementedGatherDataServiceServer) GetAllServerPools(*UserRequest, grpc.ServerStreamingServer[ServerPool]) error {
	return status.Error(codes.Unimplemented, "method GetAllServerPools not implemented")
}
func (UnimplementedGatherDataServiceServer) GetAllConfigs(*UserRequest, grpc.ServerStreamingServer[Config]) error {
	return status.Error(codes.Unimplemented, "method GetAllConfigs not implemented")
}
func (UnimplementedGatherDataServiceServer) mustEmbedUnimplementedGatherDataServiceServer() {}
func (UnimplementedGatherDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeGatherDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatherDataServiceServer will
// result in compilation errors.
type UnsafeGatherDataServiceServer interface {
	mustEmbedUnimplementedGatherDataServiceServer()
}

func RegisterGatherDataServiceServer(s grpc.ServiceRegistrar, srv GatherDataServiceServer) {
	// If the following call panics, it indicates UnimplementedGatherDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatherDataService_ServiceDesc, srv)
}

func _GatherDataService_GetAllImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatherDataServiceServer).GetAllImages(m, &grpc.GenericServerStream[UserRequest, Image]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllImagesServer = grpc.ServerStreamingServer[Image]

func _GatherDataService_GetAllFlavors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatherDataServiceServer).GetAllFlavors(m, &grpc.GenericServerStream[UserRequest, Flavor]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllFlavorsServer = grpc.ServerStreamingServer[Flavor]

func _GatherDataService_GetAllNetworks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatherDataServiceServer).GetAllNetworks(m, &grpc.GenericServerStream[UserRequest, Network]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllNetworksServer = grpc.ServerStreamingServer[Network]

func _GatherDataService_ExistServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatherDataServiceServer).ExistServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatherDataService_ExistServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatherDataServiceServer).ExistServer(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatherDataService_ExistServerPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatherDataServiceServer).ExistServerPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatherDataService_ExistServerPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatherDataServiceServer).ExistServerPools(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatherDataService_ExistConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatherDataServiceServer).ExistConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatherDataService_ExistConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatherDataServiceServer).ExistConfigs(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatherDataService_GetAllServers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatherDataServiceServer).GetAllServers(m, &grpc.GenericServerStream[UserRequest, Server]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllServersServer = grpc.ServerStreamingServer[Server]

func _GatherDataService_GetAllServerPools_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatherDataServiceServer).GetAllServerPools(m, &grpc.GenericServerStream[UserRequest, ServerPool]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllServerPoolsServer = grpc.ServerStreamingServer[ServerPool]

func _GatherDataService_GetAllConfigs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatherDataServiceServer).GetAllConfigs(m, &grpc.GenericServerStream[UserRequest, Config]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatherDataService_GetAllConfigsServer = grpc.ServerStreamingServer[Config]

// GatherDataService_ServiceDesc is the grpc.ServiceDesc for GatherDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatherDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frontcontrol.GatherDataService",
	HandlerType: (*GatherDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExistServer",
			Handler:    _GatherDataService_ExistServer_Handler,
		},
		{
			MethodName: "ExistServerPools",
			Handler:    _GatherDataService_ExistServerPools_Handler,
		},
		{
			MethodName: "ExistConfigs",
			Handler:    _GatherDataService_ExistConfigs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllImages",
			Handler:       _GatherDataService_GetAllImages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllFlavors",
			Handler:       _GatherDataService_GetAllFlavors_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllNetworks",
			Handler:       _GatherDataService_GetAllNetworks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllServers",
			Handler:       _GatherDataService_GetAllServers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllServerPools",
			Handler:       _GatherDataService_GetAllServerPools_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllConfigs",
			Handler:       _GatherDataService_GetAllConfigs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "frontcontrol.proto",
}

const (
	ConfigService_CreateConfig_FullMethodName = "/frontcontrol.ConfigService/CreateConfig"
	ConfigService_UpdateConfig_FullMethodName = "/frontcontrol.ConfigService/UpdateConfig"
	ConfigService_DeleteConfig_FullMethodName = "/frontcontrol.ConfigService/DeleteConfig"
	ConfigService_GetConfig_FullMethodName    = "/frontcontrol.ConfigService/GetConfig"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigService manages configuration settings for users.
type ConfigServiceClient interface {
	// CreateConfig creates a new configuration entry for a user.
	CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error)
	// UpdateConfig updates an existing configuration entry for a user.
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	// DeleteConfig deletes a configuration entry for a user.
	DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
	// GetConfig retrieves a configuration entry for a user.
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_CreateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// ConfigService manages configuration settings for users.
type ConfigServiceServer interface {
	// CreateConfig creates a new configuration entry for a user.
	CreateConfig(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error)
	// UpdateConfig updates an existing configuration entry for a user.
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	// DeleteConfig deletes a configuration entry for a user.
	DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	// GetConfig retrieves a configuration entry for a user.
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) CreateConfig(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConfig not implemented")
}
func (UnimplementedConfigServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedConfigServiceServer) DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_CreateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).CreateConfig(ctx, req.(*CreateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteConfig(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frontcontrol.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConfig",
			Handler:    _ConfigService_CreateConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _ConfigService_UpdateConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _ConfigService_DeleteConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ConfigService_GetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontcontrol.proto",
}

const (
	PoolService_CreatePool_FullMethodName    = "/frontcontrol.PoolService/CreatePool"
	PoolService_GetPool_FullMethodName       = "/frontcontrol.PoolService/GetPool"
	PoolService_GetAllPools_FullMethodName   = "/frontcontrol.PoolService/GetAllPools"
	PoolService_DeletePool_FullMethodName    = "/frontcontrol.PoolService/DeletePool"
	PoolService_RebuildServer_FullMethodName = "/frontcontrol.PoolService/RebuildServer"
	PoolService_AddServer_FullMethodName     = "/frontcontrol.PoolService/AddServer"
	PoolService_AddSSHKeys_FullMethodName    = "/frontcontrol.PoolService/AddSSHKeys"
	PoolService_ListStudents_FullMethodName  = "/frontcontrol.PoolService/ListStudents"
	PoolService_AddStudents_FullMethodName   = "/frontcontrol.PoolService/AddStudents"
)

// PoolServiceClient is the client API for PoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PoolService manages server pools and associated operations.
type PoolServiceClient interface {
	// CreatePool creates a new server pool for a user.
	CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error)
	// GetPool retrieves details of a specific server pool for a user.
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error)
	// GetAllPools retrieves all server pools for a user.
	GetAllPools(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPoolResponse], error)
	// DeletePool deletes a specific server pool for a user.
	DeletePool(ctx context.Context, in *DeletePoolRequest, opts ...grpc.CallOption) (*DeletePoolResponse, error)
	// RebuildServer rebuilds a server within a pool for a user.
	RebuildServer(ctx context.Context, in *RebuildServerRequest, opts ...grpc.CallOption) (*RebuildServerResponse, error)
	// AddServer adds a new server to a pool for a user.
	AddServer(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*RebuildServerResponse, error)
	// AddSSHKeys adds SSH public keys to a server pool for a user.
	AddSSHKeys(ctx context.Context, in *ListSSHPublicKeysRequest, opts ...grpc.CallOption) (*ListSSHPublicKeysResponse, error)
	// ListStudents lists students associated with a server pool for a user.
	ListStudents(ctx context.Context, in *ListStudentsRequest, opts ...grpc.CallOption) (*ListStudentsResponse, error)
	// AddStudents adds students to a server pool for a user.
	AddStudents(ctx context.Context, in *AddStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error)
}

type poolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolServiceClient(cc grpc.ClientConnInterface) PoolServiceClient {
	return &poolServiceClient{cc}
}

func (c *poolServiceClient) CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePoolResponse)
	err := c.cc.Invoke(ctx, PoolService_CreatePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoolResponse)
	err := c.cc.Invoke(ctx, PoolService_GetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) GetAllPools(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPoolResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolService_ServiceDesc.Streams[0], PoolService_GetAllPools_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPoolRequest, GetPoolResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolService_GetAllPoolsClient = grpc.ServerStreamingClient[GetPoolResponse]

func (c *poolServiceClient) DeletePool(ctx context.Context, in *DeletePoolRequest, opts ...grpc.CallOption) (*DeletePoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePoolResponse)
	err := c.cc.Invoke(ctx, PoolService_DeletePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) RebuildServer(ctx context.Context, in *RebuildServerRequest, opts ...grpc.CallOption) (*RebuildServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildServerResponse)
	err := c.cc.Invoke(ctx, PoolService_RebuildServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) AddServer(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*RebuildServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildServerResponse)
	err := c.cc.Invoke(ctx, PoolService_AddServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) AddSSHKeys(ctx context.Context, in *ListSSHPublicKeysRequest, opts ...grpc.CallOption) (*ListSSHPublicKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSSHPublicKeysResponse)
	err := c.cc.Invoke(ctx, PoolService_AddSSHKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) ListStudents(ctx context.Context, in *ListStudentsRequest, opts ...grpc.CallOption) (*ListStudentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStudentsResponse)
	err := c.cc.Invoke(ctx, PoolService_ListStudents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) AddStudents(ctx context.Context, in *AddStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddStudentResponse)
	err := c.cc.Invoke(ctx, PoolService_AddStudents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolServiceServer is the server API for PoolService service.
// All implementations must embed UnimplementedPoolServiceServer
// for forward compatibility.
//
// PoolService manages server pools and associated operations.
type PoolServiceServer interface {
	// CreatePool creates a new server pool for a user.
	CreatePool(context.Context, *CreatePoolRequest) (*CreatePoolResponse, error)
	// GetPool retrieves details of a specific server pool for a user.
	GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error)
	// GetAllPools retrieves all server pools for a user.
	GetAllPools(*GetPoolRequest, grpc.ServerStreamingServer[GetPoolResponse]) error
	// DeletePool deletes a specific server pool for a user.
	DeletePool(context.Context, *DeletePoolRequest) (*DeletePoolResponse, error)
	// RebuildServer rebuilds a server within a pool for a user.
	RebuildServer(context.Context, *RebuildServerRequest) (*RebuildServerResponse, error)
	// AddServer adds a new server to a pool for a user.
	AddServer(context.Context, *CreatePoolRequest) (*RebuildServerResponse, error)
	// AddSSHKeys adds SSH public keys to a server pool for a user.
	AddSSHKeys(context.Context, *ListSSHPublicKeysRequest) (*ListSSHPublicKeysResponse, error)
	// ListStudents lists students associated with a server pool for a user.
	ListStudents(context.Context, *ListStudentsRequest) (*ListStudentsResponse, error)
	// AddStudents adds students to a server pool for a user.
	AddStudents(context.Context, *AddStudentRequest) (*AddStudentResponse, error)
	mustEmbedUnimplementedPoolServiceServer()
}

// UnimplementedPoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolServiceServer struct{}

func (UnimplementedPoolServiceServer) CreatePool(context.Context, *CreatePoolRequest) (*CreatePoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePool not implemented")
}
func (UnimplementedPoolServiceServer) GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPool not implemented")
}
func (UnimplementedPoolServiceServer) GetAllPools(*GetPoolRequest, grpc.ServerStreamingServer[GetPoolResponse]) error {
	return status.Error(codes.Unimplemented, "method GetAllPools not implemented")
}
func (UnimplementedPoolServiceServer) DeletePool(context.Context, *DeletePoolRequest) (*DeletePoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePool not implemented")
}
func (UnimplementedPoolServiceServer) RebuildServer(context.Context, *RebuildServerRequest) (*RebuildServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildServer not implemented")
}
func (UnimplementedPoolServiceServer) AddServer(context.Context, *CreatePoolRequest) (*RebuildServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddServer not implemented")
}
func (UnimplementedPoolServiceServer) AddSSHKeys(context.Context, *ListSSHPublicKeysRequest) (*ListSSHPublicKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSSHKeys not implemented")
}
func (UnimplementedPoolServiceServer) ListStudents(context.Context, *ListStudentsRequest) (*ListStudentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStudents not implemented")
}
func (UnimplementedPoolServiceServer) AddStudents(context.Context, *AddStudentRequest) (*AddStudentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddStudents not implemented")
}
func (UnimplementedPoolServiceServer) mustEmbedUnimplementedPoolServiceServer() {}
func (UnimplementedPoolServiceServer) testEmbeddedByValue()                     {}

// UnsafePoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolServiceServer will
// result in compilation errors.
type UnsafePoolServiceServer interface {
	mustEmbedUnimplementedPoolServiceServer()
}

func RegisterPoolServiceServer(s grpc.ServiceRegistrar, srv PoolServiceServer) {
	// If the following call panics, it indicates UnimplementedPoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolService_ServiceDesc, srv)
}

func _PoolService_CreatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).CreatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_CreatePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).CreatePool(ctx, req.(*CreatePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_GetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_GetAllPools_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPoolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PoolServiceServer).GetAllPools(m, &grpc.GenericServerStream[GetPoolRequest, GetPoolResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolService_GetAllPoolsServer = grpc.ServerStreamingServer[GetPoolResponse]

func _PoolService_DeletePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).DeletePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_DeletePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).DeletePool(ctx, req.(*DeletePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_RebuildServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).RebuildServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_RebuildServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).RebuildServer(ctx, req.(*RebuildServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_AddServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).AddServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_AddServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).AddServer(ctx, req.(*CreatePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_AddSSHKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSSHPublicKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).AddSSHKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_AddSSHKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).AddSSHKeys(ctx, req.(*ListSSHPublicKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_ListStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).ListStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_ListStudents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).ListStudents(ctx, req.(*ListStudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_AddStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).AddStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_AddStudents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).AddStudents(ctx, req.(*AddStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolService_ServiceDesc is the grpc.ServiceDesc for PoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frontcontrol.PoolService",
	HandlerType: (*PoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePool",
			Handler:    _PoolService_CreatePool_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _PoolService_GetPool_Handler,
		},
		{
			MethodName: "DeletePool",
			Handler:    _PoolService_DeletePool_Handler,
		},
		{
			MethodName: "RebuildServer",
			Handler:    _PoolService_RebuildServer_Handler,
		},
		{
			MethodName: "AddServer",
			Handler:    _PoolService_AddServer_Handler,
		},
		{
			MethodName: "AddSSHKeys",
			Handler:    _PoolService_AddSSHKeys_Handler,
		},
		{
			MethodName: "ListStudents",
			Handler:    _PoolService_ListStudents_Handler,
		},
		{
			MethodName: "AddStudents",
			Handler:    _PoolService_AddStudents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllPools",
			Handler:       _PoolService_GetAllPools_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "frontcontrol.proto",
}

const (
	UserService_UpdateDataUser_FullMethodName    = "/frontcontrol.UserService/UpdateDataUser"
	UserService_AddPersonalSSHKey_FullMethodName = "/frontcontrol.UserService/AddPersonalSSHKey"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserService streams updates related to user data such as server pools, servers, and configurations.
type UserServiceClient interface {
	// UpdateDataUser streams updates related to user data.
	UpdateDataUser(ctx context.Context, in *UpdateDataUserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateDataUserResponse], error)
	// AddPersonalSSHKey adds a personal SSH key for a user.
	AddPersonalSSHKey(ctx context.Context, in *AddPersonalSSHKeyRequest, opts ...grpc.CallOption) (*AddPersonnalSSHKeyResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UpdateDataUser(ctx context.Context, in *UpdateDataUserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateDataUserResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_UpdateDataUser_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateDataUserRequest, UpdateDataUserResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_UpdateDataUserClient = grpc.ServerStreamingClient[UpdateDataUserResponse]

func (c *userServiceClient) AddPersonalSSHKey(ctx context.Context, in *AddPersonalSSHKeyRequest, opts ...grpc.CallOption) (*AddPersonnalSSHKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPersonnalSSHKeyResponse)
	err := c.cc.Invoke(ctx, UserService_AddPersonalSSHKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// UserService streams updates related to user data such as server pools, servers, and configurations.
type UserServiceServer interface {
	// UpdateDataUser streams updates related to user data.
	UpdateDataUser(*UpdateDataUserRequest, grpc.ServerStreamingServer[UpdateDataUserResponse]) error
	// AddPersonalSSHKey adds a personal SSH key for a user.
	AddPersonalSSHKey(context.Context, *AddPersonalSSHKeyRequest) (*AddPersonnalSSHKeyResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) UpdateDataUser(*UpdateDataUserRequest, grpc.ServerStreamingServer[UpdateDataUserResponse]) error {
	return status.Error(codes.Unimplemented, "method UpdateDataUser not implemented")
}
func (UnimplementedUserServiceServer) AddPersonalSSHKey(context.Context, *AddPersonalSSHKeyRequest) (*AddPersonnalSSHKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPersonalSSHKey not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_UpdateDataUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateDataUserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).UpdateDataUser(m, &grpc.GenericServerStream[UpdateDataUserRequest, UpdateDataUserResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_UpdateDataUserServer = grpc.ServerStreamingServer[UpdateDataUserResponse]

func _UserService_AddPersonalSSHKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPersonalSSHKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddPersonalSSHKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddPersonalSSHKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddPersonalSSHKey(ctx, req.(*AddPersonalSSHKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frontcontrol.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPersonalSSHKey",
			Handler:    _UserService_AddPersonalSSHKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateDataUser",
			Handler:       _UserService_UpdateDataUser_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "frontcontrol.proto",
}

const (
	AttribVMService_AttribVMinPool_FullMethodName    = "/frontcontrol.AttribVMService/AttribVMinPool"
	AttribVMService_ReturnPoolWithKey_FullMethodName = "/frontcontrol.AttribVMService/ReturnPoolWithKey"
)

// AttribVMServiceClient is the client API for AttribVMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AttribVMService handles VM attribution based on public keys.
type AttribVMServiceClient interface {
	// AttribVMinPool attributes a VM in the pool to a user based on the public key.
	AttribVMinPool(ctx context.Context, in *AttribVMinPoolRequest, opts ...grpc.CallOption) (*AttribVMinPoolResponse, error)
	// ReturnPoolWithKey returns the pools associated with a given public key.
	ReturnPoolWithKey(ctx context.Context, in *PoolWithKeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PoolWithKeyResponse], error)
}

type attribVMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttribVMServiceClient(cc grpc.ClientConnInterface) AttribVMServiceClient {
	return &attribVMServiceClient{cc}
}

func (c *attribVMServiceClient) AttribVMinPool(ctx context.Context, in *AttribVMinPoolRequest, opts ...grpc.CallOption) (*AttribVMinPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttribVMinPoolResponse)
	err := c.cc.Invoke(ctx, AttribVMService_AttribVMinPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attribVMServiceClient) ReturnPoolWithKey(ctx context.Context, in *PoolWithKeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PoolWithKeyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AttribVMService_ServiceDesc.Streams[0], AttribVMService_ReturnPoolWithKey_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PoolWithKeyRequest, PoolWithKeyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttribVMService_ReturnPoolWithKeyClient = grpc.ServerStreamingClient[PoolWithKeyResponse]

// AttribVMServiceServer is the server API for AttribVMService service.
// All implementations must embed UnimplementedAttribVMServiceServer
// for forward compatibility.
//
// AttribVMService handles VM attribution based on public keys.
type AttribVMServiceServer interface {
	// AttribVMinPool attributes a VM in the pool to a user based on the public key.
	AttribVMinPool(context.Context, *AttribVMinPoolRequest) (*AttribVMinPoolResponse, error)
	// ReturnPoolWithKey returns the pools associated with a given public key.
	ReturnPoolWithKey(*PoolWithKeyRequest, grpc.ServerStreamingServer[PoolWithKeyResponse]) error
	mustEmbedUnimplementedAttribVMServiceServer()
}

// UnimplementedAttribVMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttribVMServiceServer struct{}

func (UnimplementedAttribVMServiceServer) AttribVMinPool(context.Context, *AttribVMinPoolRequest) (*AttribVMinPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttribVMinPool not implemented")
}
func (UnimplementedAttribVMServiceServer) ReturnPoolWithKey(*PoolWithKeyRequest, grpc.ServerStreamingServer[PoolWithKeyResponse]) error {
	return status.Error(codes.Unimplemented, "method ReturnPoolWithKey not implemented")
}
func (UnimplementedAttribVMServiceServer) mustEmbedUnimplementedAttribVMServiceServer() {}
func (UnimplementedAttribVMServiceServer) testEmbeddedByValue()                         {}

// UnsafeAttribVMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttribVMServiceServer will
// result in compilation errors.
type UnsafeAttribVMServiceServer interface {
	mustEmbedUnimplementedAttribVMServiceServer()
}

func RegisterAttribVMServiceServer(s grpc.ServiceRegistrar, srv AttribVMServiceServer) {
	// If the following call panics, it indicates UnimplementedAttribVMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttribVMService_ServiceDesc, srv)
}

func _AttribVMService_AttribVMinPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttribVMinPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttribVMServiceServer).AttribVMinPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttribVMService_AttribVMinPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttribVMServiceServer).AttribVMinPool(ctx, req.(*AttribVMinPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttribVMService_ReturnPoolWithKey_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PoolWithKeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AttribVMServiceServer).ReturnPoolWithKey(m, &grpc.GenericServerStream[PoolWithKeyRequest, PoolWithKeyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttribVMService_ReturnPoolWithKeyServer = grpc.ServerStreamingServer[PoolWithKeyResponse]

// AttribVMService_ServiceDesc is the grpc.ServiceDesc for AttribVMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttribVMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frontcontrol.AttribVMService",
	HandlerType: (*AttribVMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttribVMinPool",
			Handler:    _AttribVMService_AttribVMinPool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReturnPoolWithKey",
			Handler:       _AttribVMService_ReturnPoolWithKey_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "frontcontrol.proto",
}
